Handle the interim new case
Pearson-Advance/openedx-external-enrollments pull request #40
Opened 2021-07-30 11:46 UTC by Jacatove

# Description:
This PR has the purpose to extend the SF integration to handle a new case, which consists of a program purchase type with no program metadata, therefore the SF external controller must get the data from the first course with SF metadata.

Ticket: [PAE-781](https://pearsonadvance.atlassian.net/browse/PAE-781)

 does not exist and bundle type = 'special offer', then pick-up POI/IH from first course with SF metadata (expected to be the non-HZ course)

2021-08-02 22:18 UTC, ivanvgh requested changes

2021-08-02 22:18 UTC, ivanvgh commented on openedx_external_enrollments/external_enrollments/salesforce_external_enrollment.py
> +                elif self._is_special_program_type(program.get("type")):
This way you won't need the method `_is_special_program_type` and also to reduce unnecessary code lines, what do you think?
```suggestion
                elif program.get("type") == CUSTOM_BUNDLE_TYPE:
```

2021-08-02 22:18 UTC, ivanvgh commented on openedx_external_enrollments/external_enrollments/salesforce_external_enrollment.py
> +CUSTOM_BUNDLE_TYPE = 'special offer'
Since this is particular to the SalesforceEnrollment class, you can move it there, what do you think @Jacatove?
```suggestion
```

2021-08-02 22:18 UTC, ivanvgh commented on openedx_external_enrollments/external_enrollments/salesforce_external_enrollment.py
> +    def _get_program_of_interest_from_courses(self, order_lines):
@Jacatove, how do we assert that  it is a non-HZ course?

2021-08-02 22:18 UTC, ivanvgh commented on openedx_external_enrollments/tests/external_enrollments/tests_salesforce_external_enrollment.py
> +        """This test validates that in a program purchase, if program metadata is empty and program typeis
```suggestion
        """This test validates that in a program purchase, if program metadata is empty and program type is
```

2021-08-02 22:18 UTC, ivanvgh commented on openedx_external_enrollments/tests/external_enrollments/tests_salesforce_external_enrollment.py
> +
@Jacatove, `_get_program_of_interest_from_courses` unit test is missing.

2021-08-02 22:18 UTC, ivanvgh commented on openedx_external_enrollments/tests/external_enrollments/tests_salesforce_external_enrollment.py
> +    def test_get_program_of_interest_data_from_program(self, get_course_mock, get_user_mock, model_mock):
@Jacatove, I see there are two unit tests cases here, could you split it up, please?

2021-08-04 20:57 UTC, diegomillan submitted a review, later dismissed

2021-08-04 22:20 UTC, ivanvgh commented on openedx_external_enrollments/external_enrollments/salesforce_external_enrollment.py
> +    def _get_program_of_interest_from_courses(self, order_lines):
Alright, you can leave it as it is now.

2021-08-04 22:20 UTC, ivanvgh submitted a review, later dismissed

2021-08-05 13:49 UTC, ivanvgh approved these changes

2021-08-05 14:25 UTC, diegomillan approved these changes

2021-08-05 14:34 UTC, merged