PAE-702.3 - Update data format and use EnrollmentRequestLog.
Pearson-Advance/openedx-external-enrollments pull request #45
Opened 2021-09-02 14:43 UTC by Jacatove

# Description:
This PR is intended to add the username, first name and last name in the string that is returned by `_get_enrollment_data` and also use `EnrollmentRequestLog` to persist logging information related to the enrollment.

2021-09-02 21:24 UTC, ivanvgh requested changes

2021-09-02 21:24 UTC, ivanvgh commented on openedx_external_enrollments/external_enrollments/pathstream_external_enrollment.py
> +            LOG.error(error_msg)
@Jacatove, would you add a blank line before this one, please?

2021-09-03 13:48 UTC, Jacatove commented on openedx_external_enrollments/external_enrollments/pathstream_external_enrollment.py
> +            'data': str(data),
@ivanvgh Within data comes a 'CourseLocator' which is not JSON serialiazable. That is why I made the string conversion.

2021-09-03 15:05 UTC, ivanvgh commented on openedx_external_enrollments/external_enrollments/pathstream_external_enrollment.py
> +            'data': str(data),
Got it!

2021-09-03 15:09 UTC, ivanvgh requested changes

2021-09-03 15:09 UTC, ivanvgh commented on openedx_external_enrollments/external_enrollments/pathstream_external_enrollment.py
> +            LOG.error(error_msg)
@Jacatove, I meant before not after. To separate assignment to action statements.

2021-09-03 15:24 UTC, ivanvgh requested changes

2021-09-03 15:24 UTC, ivanvgh commented on openedx_external_enrollments/external_enrollments/pathstream_external_enrollment.py
> +
@Jacatove, please would you remove this unnecessary blank line?

2021-09-03 15:24 UTC, ivanvgh commented on openedx_external_enrollments/external_enrollments/pathstream_external_enrollment.py
>              enrollment.meta.append(
@Jacatove, would you add a blank line before this one?

2021-09-03 15:24 UTC, ivanvgh commented on openedx_external_enrollments/external_enrollments/pathstream_external_enrollment.py
> +        log_details = {
@Jacatove, please add a blank line before this one.

2021-09-03 15:24 UTC, ivanvgh commented on openedx_external_enrollments/external_enrollments/pathstream_external_enrollment.py
> +        }
@Jacatove, please add a blank line to separate the try block.

2021-09-03 16:52 UTC, ivanvgh requested changes

2021-09-03 16:52 UTC, ivanvgh commented on openedx_external_enrollments/external_enrollments/pathstream_external_enrollment.py
@Jacatove, please address this one.

2021-09-03 16:52 UTC, ivanvgh commented on openedx_external_enrollments/external_enrollments/pathstream_external_enrollment.py
>              enrollment.meta.append(
@Jacatove, please address this one.

2021-09-03 18:28 UTC, ivanvgh approved these changes

2021-09-03 20:08 UTC, diegomillan approved these changes

2021-09-08 15:09 UTC, ivanvgh submitted a review, later dismissed

2021-09-09 19:39 UTC, diegomillan submitted a review, later dismissed

2021-09-09 20:20 UTC, ivanvgh approved these changes

2021-09-13 15:48 UTC, diegomillan approved these changes

2021-09-13 16:01 UTC, merged