PAE-702.4 - Fix upgrade dependencies, add boto3 and botocore.
Pearson-Advance/openedx-external-enrollments pull request #46
Opened 2021-09-06 15:01 UTC by Jacatove

# Description:
This PR is intended to fix some dependencies in order to work with python 3.5. Some context: when adding boto3 and botocore, It was necessary to run `$ make upgrade` , then the latest versions of the dependencies started to be downloaded but some of them were no longer compatible with python 3.5.

2021-09-07 04:22 UTC, diegomillan requested changes

2021-09-07 04:22 UTC, diegomillan commented on requirements/base.in
> +botocore
Please add a newline at the end of the file. @Jacatove

2021-09-08 02:49 UTC, Squirrel18 approved these changes

2021-09-08 03:22 UTC, diegomillan approved these changes

2021-09-08 13:37 UTC, merged