PAE 830 - Update Greenfig integration.
Pearson-Advance/openedx-external-enrollments pull request #49
Opened 2021-09-27 16:54 UTC by Jacatove

# Description:
Currently, the Greenfig integration saves the entire content of the enrollment log file in every `EnrollmentRequestLog` object, It should only contain information relating to the enrollment event that triggered the the Greenfig controller.

2021-09-29 21:18 UTC, diegomillan requested changes

2021-09-29 21:18 UTC, diegomillan commented on openedx_external_enrollments/external_enrollments/greenfig_external_enrollment.py
> +    def _post_enrollment(self, data, course_settings=None):
We are duplicating code. This is the same method defined in the base class. @Jacatove

2021-09-29 22:36 UTC, diegomillan approved these changes
It is approved @Jacatove . Let's keep an eye on how to redefine the code structure before migration.

2021-09-30 10:26 UTC, ivanvgh commented on openedx_external_enrollments/external_enrollments/greenfig_external_enrollment.py
> +            return str(error), status.HTTP_400_BAD_REQUEST
@Jacatove, please add a blank line before this one.

2021-09-30 10:26 UTC, ivanvgh commented on openedx_external_enrollments/tests/external_enrollments/test_greenfig_external_enrollment.py
> +        expected_file_data += expected_enrollment_data
@Jacatove, can we keep this in a single assignment?
```suggestion
        expected_file_data = dropbox_response_text + expected_enrollment_data
```

2021-10-12 11:27 UTC, ivanvgh submitted a review, later dismissed
LGTM

2021-10-12 19:41 UTC, diegomillan submitted a review, later dismissed

2021-11-30 18:26 UTC, ivanvgh approved these changes

2021-11-30 18:48 UTC, diegomillan approved these changes

2021-12-02 13:26 UTC, merged