PAE-130 | Enable/disable Salesforce enrollments per site
Pearson-Advance/openedx-external-enrollments pull request #55
Opened 2022-03-24 18:43 UTC by diegomillan

This PR allows activating the Salesforce enrollment controller using a per site criteria.

[Context](https://agile-jira.pearson.com/browse/PAE-130)

2022-03-24 22:04 UTC, NeOneSoft approved these changes
lgtm

2022-03-24 22:55 UTC, Squirrel18 requested changes

2022-03-24 22:55 UTC, Squirrel18 commented on openedx_external_enrollments/api/v0/views.py
> +                LOG.info("Salesforce enrollment controller not enabled for this site")
nit: Missing period at the end of the text. @diegomillan

2022-03-24 22:55 UTC, Squirrel18 commented on openedx_external_enrollments/api/v0/views.py
> +                    {"info": "Salesforce enrollment controller not enabled for this site"},
nit: Missing period at the end of the text. @diegomillan If you want, you can create a variable for this text since it's used twice.

2022-03-24 22:55 UTC, Squirrel18 commented on openedx_external_enrollments/api/v0/views.py
> +                    status=status.HTTP_200_OK
nit: Trailing comma. @diegomillan

2022-03-24 22:55 UTC, Squirrel18 commented on openedx_external_enrollments/api/v0/views.py
> +                status=status.HTTP_200_OK
nit: Trailing comma. @diegomillan

2022-04-05 02:03 UTC, NeOneSoft approved these changes
lgtm

2022-04-05 14:38 UTC, Squirrel18 submitted a review, later dismissed

2022-04-05 15:38 UTC, NeOneSoft submitted a review, later dismissed

2022-04-05 15:52 UTC, Squirrel18 submitted a review, later dismissed

2022-04-05 17:37 UTC, NeOneSoft approved these changes

2022-04-05 17:37 UTC, merged